# docker/fluentd/conf/fluent.conf
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter auth-service.**>
  @type parser
  key_name log
  reserve_data true
  <parse>
    @type json
    json_parser json
  </parse>
</filter>

<match auth-service.**>
  @type elasticsearch
  host elasticsearch
  port 9200
  logstash_format true
  logstash_prefix auth-service
  include_tag_key true
  tag_key @log_name
  flush_interval 5s
  reconnect_on_error true
  reload_on_failure true
  request_timeout 15s
</match>

# For debugging
<match **>
  @type stdout
</match>